= `clj-commons/clj-yaml`
:lib-version: 0.7.110
:project-coords: clj-commons/clj-yaml

Provides http://yaml.org[YAML] encoding and decoding for Clojure via the https://bitbucket.org/snakeyaml/snakeyaml[snakeyaml] Java library.

// Badges
https://clojars.org/{project-coords}[image:https://img.shields.io/clojars/v/{project-coords}.svg[Clojars Project]] 
https://cljdoc.org/d/{project-coords}[image:https://cljdoc.org/badge/{project-coords}[cljdoc badge]] 
https://circleci.com/gh/{project-coords}[image:https://circleci.com/gh/{project-coords}.svg?style=svg[CircleCI Status]] 
https://babashka.org[image:https://raw.githubusercontent.com/babashka/babashka/master/logo/built-in-badge.svg[bb built-in]]
https://clojurians.slack.com/archives/C042XAQFCCU[image:https://img.shields.io/badge/slack-join_chat-brightgreen.svg[Slack chat]]

(This is a maintained fork of https://github.com/CircleCI-Archived/clj-yaml[the circleci fork] which forked from https://github.com/lancepantz/clj-yaml[the original])

== Usage

[source,clojure]
----
(require '[clj-yaml.core :as yaml])

(yaml/generate-string
  [{:name "John Smith", :age 33}
   {:name "Mary Smith", :age 27}])
"- {name: John Smith, age: 33}\n- {name: Mary Smith, age: 27}\n"

(yaml/parse-string "
- {name: John Smith, age: 33}
- name: Mary Smith
  age: 27
")
=> ({:name "John Smith", :age 33}
    {:name "Mary Smith", :age 27})
----

By default, keys are converted to clojure keywords. To prevent this, add `:keywords false` parameters to the `parse-string` function:

[source,clojure]
----
(yaml/parse-string "
- {name: John Smith}
" :keywords false)
----

Unknown tags can be handled by passing a handler function via the
`:unknown-tag-fn` parameter. The handler function is provided a map which
includes `:tag` and `:value` keys. Note that the value passed to the
`unknown-tag-fn` is a string if it's a scalar, regardless of the quoting (or
lack thereof) of the scalar value.

[source,clojure]
----
;; drop tags
(yaml/parse-string "!Base12 10" :unknown-tag-fn :value
;; => "10"
(yaml/parse-string "!Base12 10"
                   :unknown-tag-fn (fn [{:keys [tag value]}]
                                      (if (= "!Base12" tag)
                                          (Integer/parseInt value 12)
                                          value)))
;; => 12
----

Different flow styles (`:auto`, `:block`, `:flow`) allow customization of how YAML is rendered:

[source,clojure]
----
(yaml/generate-string some-data :dumper-options {:flow-style :block})
----

Use the `:indent` (default: `2`) and `:indicator-indent` (default: `0`) options to adjust indentation:

[source,clojure]
----
(yaml/generate-string some-data :dumper-options {:indent 6
                                                 :indicator-indent 3
                                                 :flow-style :block})
=>
todo:
   -  name: Fix issue
      responsible:
            name: Rita
----

`:indent` must always be larger than `:indicator-indent`. If only 1 higher, the indicator will be on a separate line:

[source,clojure]
----
(yaml/generate-string some-data :dumper-options {:indent 2
                                                 :indicator-indent 1
                                                 :flow-style :block})
=>
todo:
 -
  name: Fix issue
  responsible:
    name: Rita
----

== Installation

`clj-commons/clj-yaml` is available as a Maven artifact from http://clojars.org/clj-commons/clj-yaml[Clojars].

=== Leiningen/Boot

[source,clojure,subs="attributes+"]
----
[clj-commons/clj-yaml "{lib-version}"]
----

=== Clojure CLI/`deps.edn`

[source,clojure,subs="attributes+"]
----
clj-commons/clj-yaml {:mvn/version "{lib-version}"}
----

== Development

[source,shell]
----
$ git clone git://github.com/clj-commons/clj-yaml.git
$ lein deps
$ lein test
$ lein install
----

== Use as git dependency

To get the latest changes that are not yet released to Clojars, you can use this library as a git dependency:

[source,clojure]
----
$ cat deps.edn
{:deps {clj-commons/clj-yaml {:git/url "https://github.com/clj-commons/clj-yaml"
                              :git/sha "05eaca35c34c092ffdd2e620ef07962ce147a88b"}}}

$ clj -X:deps prep
$ clj -M -e "(require '[clj-yaml.core :as yaml])"
----

== People

=== Contributors
A huge thank you to https://github.com/clj-commons/clj-yaml/graphs/contributors[all the people who have contributed directly to clj-yaml]!

=== Founders

* https://github.com/lancepantz[@lancepantz] - the creator or clj-yaml
* https://github.com/marcomorain[@marcomorain] - the holder of the torch for the CircleCI fork

=== Current Active Maintainers

* https://github.com/borkdude[@borkdude]
* https://github.com/lread[@lread]

== License
(c) Lance Bradley - Licensed under the same terms as clojure itself. See LICENCE file for details.
Portions (c) Owain Lewis as marked.
