name: tests
on:
  # allow this workflow to be called from other workflows, namely: publish
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-kondo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/shared-setup
        with:
          jdk: '11'

      - name: Lint
        run: bb lint-kondo

  lint-eastwood:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/shared-setup
        with:
          jdk: '11'

      - name: Lint
        run: bb lint-eastwood

  test:
    runs-on: ${{ matrix.os.name }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [{name: 'windows', shell: 'pwsh'}, {name: 'ubuntu', shell: 'bash'}]
        jdk: ['8', '11', '17', '21', '23']

    name: ${{matrix.os.name}} jdk ${{ matrix.jdk }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/workflows/shared-setup
      with:
        jdk: ${{ matrix.jdk }}
        shell: ${{ matrix.os.shell }}

    - name: Compile java
      run: bb compile-java

    - name: Run tests
      run: bb test --clj-version :all

  test-native:
    runs-on: ${{matrix.os.name}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [{name: 'windows', shell: 'pwsh'}, {name: 'ubuntu', shell: 'bash'}]
        distribution:
          - { name: 'graalvm', short-name: 'graal' }
          - { name: 'graalvm-community', short-name: 'graalce' }
        java-version:
          - '24'
        clojure-version: [ '1.12' ]

    name: ${{matrix.os.name}} ${{matrix.distribution.short-name}} jdk${{matrix.java-version}} clj${{ matrix.clojure-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/workflows/shared-setup
      with:
        jdk: skip
        shell: ${{ matrix.os.shell }}

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution.name }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run native tests
      run: bb test-native --clj-version ${{ matrix.clojure-version }}
